sudo: required

language: python

python:
    - "2.7"

install:
    - pip install -r requirements.txt

before_script: 
    - psql -c 'create database test;' -U postgres
    - chmod +x script.sh

script:
    - ./script.sh