sudo: required

language: python

python:
    - "2.7"

install:
    - pip install -r requirements.txt

before_script: 
    - psql -c 'create database test;' -U postgres


script:
    - bash checkfile.bash

# ignore push events to this branch
branches:
  except:
    - travis-ci