FORMAT: 1A
HOST: http://www.superheroes-idb.tk/

# Superheroes
Superheroes API is a way to access information about Marvel superheroes and villains, including characters,
comic books, and TV shows.

# Group Characters
Character related resources of the **Superheroes API**

##Character Collection [/characters/]
A list of all characters in the database. The list is inside a dictionary and can be accessed using the
"Characters" key. The list contains the names and ids of each character in the database. The id can be
used to look up a character or in a link to a page, for example.
### List all Characters [GET]
+ Response 200 (application/json)

    + Body

                {
                  "Characters": [
                    {
                      "id": "1", 
                      "name": "Captain America"
                    }, 
                    {
                      "id": "2", 
                      "name": "Spider Man"
                    }, 
                    {
                      "id": "3", 
                      "name": "Thor"
                    }, 
                    {
                      "id": "4", 
                      "name": "Storm"
                    }, 
                    {
                      "id": "5", 
                      "name": "Invisible Woman"
                    }, 
                    {
                      "id": "6", 
                      "name": "Ultron"
                    }, 
                    {
                      "id": "7", 
                      "name": "Loki"
                    }, 
                    {
                      "id": "8", 
                      "name": "Magneto"
                    }, 
                    {
                      "id": "9", 
                      "name": "Mystique"
                    }, 
                    {
                      "id": "10", 
                      "name": "Ronan"
                    }
                  ]
                }

##Character [/characters/{id}]
Info on a given character in the Marvel universe. The info is in a dictionary with keys such as
"aliases" and "name." Also contains a list of related comics at the key "comics" and related shows
at the key "shows."

+ Parameters
    + id (required, number, `1`) ... Unique integer ID for the character.

### Retrieve a character [GET]
+ Response 200 (application/json)

    + Body
    
                {
                  "aliases": [
                    "Steven Grant Rodgers", 
                    "Winghead", 
                    "Shield-Slinger", 
                    "The First Avenger", 
                    "Sentinel of Liberty", 
                    "The Living Legend", 
                    "Star-Spangled Avenger"
                  ], 
                  "alignment": "Good", 
                  "comics": [
                    {
                      "id": "2", 
                      "name": "Amazing Spider-Man"
                    }, 
                    {
                      "id": "3", 
                      "name": "Avengers"
                    }, 
                    {
                      "id": "5", 
                      "name": "Incredible Hulk"
                    }, 
                    {
                      "id": "6", 
                      "name": "S.H.I.E.L.D."
                    }
                  ], 
                  "description": "In World War II patriotic solider Steve Rogers recipient of the \"Super Soldier Serum\" became the living symbol of freedom, Captain America. Left for dead while frozen in ice, the star-spangled hero with an indestructible shield awoke years later to continue his never-ending battle for liberty.", 
                  "gender": "Male", 
                  "id": 1, 
                  "name": "Captain America", 
                  "picture": "http://i.imgur.com/hPsu2lH.png", 
                  "powers": [
                    "Superhuman", 
                    "Boxing", 
                    "Judo"
                  ], 
                  "shows": [
                    {
                      "id": "1", 
                      "name": "Agents of S.H.I.E.L.D."
                    }, 
                    {
                      "id": "2", 
                      "name": "Ultimate Spider-Man"
                    }, 
                    {
                      "id": "4", 
                      "name": "Fantastic Four"
                    }, 
                    {
                      "id": "5", 
                      "name": "Iron Man"
                    }, 
                    {
                      "id": "6", 
                      "name": "The Incredible Hulk"
                    }
                  ], 
                  "universe": "Earth-616"
                }


# Group Comic Books
Comic book related resources of the **Superheroes API**

##Comic Book Collection [/comics/]
A list of all comic books in the database. The list is inside a dictionary and can be accessed using the
"Comics" key. The list contains the names and ids of each comic in the database. The id can be
used to look up a comic or in a link to a page, for example.
### List all Comic Books [GET]
+ Response 200 (application/json)

    + Body

                {
                  "Comics": [
                    {
                      "id": "1", 
                      "name": "Fantastic Four"
                    }, 
                    {
                      "id": "2", 
                      "name": "Amazing Spider-Man"
                    }, 
                    {
                      "id": "3", 
                      "name": "Avengers"
                    }, 
                    {
                      "id": "4", 
                      "name": "Kick-Ass"
                    }, 
                    {
                      "id": "5", 
                      "name": "Incredible Hulk"
                    }, 
                    {
                      "id": "6", 
                      "name": "S.H.I.E.L.D."
                    }, 
                    {
                      "id": "7", 
                      "name": "Daredevil"
                    }, 
                    {
                      "id": "8", 
                      "name": "Legendary Star-Lord"
                    }, 
                    {
                      "id": "9", 
                      "name": "Raiders of the Lost Ark"
                    }, 
                    {
                      "id": "10", 
                      "name": "James Bond, Jr"
                    }
                  ]
                }

##Comic Book [/comics/{id}]
Info on a given Marvel comic book. The info is in a dictionary with keys such as
"issues" and "name." Also contains a list of related characters at the key "characters."

+ Parameters
    + id (required, number, `1`) ... Unique integer ID for the comic book.

### Retrieve a comic book [GET]
+ Response 200 (application/json)

    + Body
    
                {
                  "characters": [
                    {
                      "id": "2", 
                      "name": "Spider Man"
                    }, 
                    {
                      "id": "5", 
                      "name": "Invisible Woman"
                    }
                  ], 
                  "description": "The Fantastic Four is a fictional superhero team appearing in comic books published by Marvel Comics. The group debuted in The Fantastic Four #1 (cover dated Nov. 1961), which helped to usher in a new level of realism in the medium.", 
                  "id": 1, 
                  "issues": 50, 
                  "name": "Fantastic Four", 
                  "picture": "http://i.imgur.com/psn8PsY.jpg", 
                  "pubend": "1966", 
                  "pubstart": "1961", 
                  "universe": "Earth-616", 
                  "volumes": 1
                }
        
        
# Group TV Shows
TV Show related resources of the **Superheroes API**

##TV Show Collection [/shows/]
A list of all TV shows in the database. The list is inside a dictionary and can be accessed using the
"Shows" key. The list contains the names and ids of each show in the database. The id can be
used to look up a show or in a link to a page, for example.

### List all TV Shows [GET]
+ Response 200 (application/json)

    + Body

                {
                  "Shows": [
                    {
                      "id": "1", 
                      "name": "Agents of S.H.I.E.L.D."
                    }, 
                    {
                      "id": "2", 
                      "name": "Ultimate Spider-Man"
                    }, 
                    {
                      "id": "3", 
                      "name": "Mutant X"
                    }, 
                    {
                      "id": "4", 
                      "name": "Fantastic Four"
                    }, 
                    {
                      "id": "5", 
                      "name": "Iron Man"
                    }, 
                    {
                      "id": "6", 
                      "name": "The Incredible Hulk"
                    }, 
                    {
                      "id": "7", 
                      "name": "Silver Surfer"
                    }, 
                    {
                      "id": "8", 
                      "name": "Black Panther"
                    }, 
                    {
                      "id": "9", 
                      "name": "X-Men"
                    }, 
                    {
                      "id": "10", 
                      "name": "X-Men: Evolution"
                    }
                  ]
                }

##TV show [/shows/{id}]
Info on a given Marvel TV show. The info is in a dictionary with keys such as
"broadcaster" and "name." Also contains a list of related characters at the key "characters."

+ Parameters
    + id (required, number, `1`) ... Unique integer ID for the TV show.

### Retrieve a TV show [GET]
+ Response 200 (application/json)

    + Body
    
                {
                  "broadcaster": "ABC", 
                  "characters": [
                    {
                      "id": "1", 
                      "name": "Captain America", 
                      "type": "character"
                    }, 
                    {
                      "id": "4", 
                      "name": "Storm", 
                      "type": "character"
                    }
                  ], 
                  "description": "The series revolves around the character of Phil Coulson, with Clark Gregg reprising his role from the film series, and his team of S.H.I.E.L.D. agents, who must deal with various unusual cases and enemies.", 
                  "enddate": "", 
                  "episodes": 35, 
                  "id": 1, 
                  "name": "Agents of S.H.I.E.L.D.", 
                  "picture": "http://i.imgur.com/NCP2DvC.jpg", 
                  "seasons": 2, 
                  "startdate": "9/24/2013", 
                  "universe": "Earth-616"
                }